{% set version = "1.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-import
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/import_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/import/import_{{ version }}.tar.gz
  sha256: 322c6ba2a588e5a4068a4127d66852a56e5e2b2497be0c0b60e6582cd19bea59

build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:

  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('import')"           # [not win]
    - "\"%R%\" -e \"library('import')\""  # [win]

about:
  home: https://github.com/smbache/import
  license: MIT
  summary: This is an alternative mechanism for importing objects from packages. The syntax allows for importing multiple objects from a package with a single command in an expressive way. The import package bridges some of the gap between using library (or require) and direct (single-object) imports. Furthermore the imported
    objects are not placed in the current environment. It is also possible to import objects from stand-alone .R files. For more information, refer to the package vignette.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
